### PR TITLE
Backend cleanup

### PR DESCRIPTION
**Pull request by AdamPellot**
A meeting held on 8/1/21 concluded that routes for hackathon categories and hackathon groups were not needed.

### CODE REVIEW

**Review by TorrentofShame — APPROVED** [review]
Looks good, just needs merge conflicts resolved.

**Comment by APherwani** [comment]
Why was this approved when tests were failing?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TorrentofShame** [comment]
Tests are not failing

**Comment by APherwani** [comment]
Ahh I see, this is code coverage check

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by TorrentofShame** [comment]
Still looks good

**Pull request merged**
